package com.serverapi.utilities;

public enum TechnionRankerFunctions {
  INSERT_COURSE("INSERT_COURSE"), GET_COURSE("GET_COURSE"), INSERT_PROFESSOR(
      "INSERT_PROFESSOR"), GET_PROFESSOR("GET_PROFESSOR"), INSERT_STUDENT_USER(
      "INSERT_STUDENT_USER"), GET_STUDENT_USER("GET_STUDENT_USER"),
  INSERT_STUDENT_PROFESSOR_COURSE("INSERT_STUDENT_PROFESSOR_COURSE"),
  GET_STUDENT_PROFESSOR_COURSE("GET_STUDENT_PROFESSOR_COURSE"),
  GET_STUDENT_PROFESSORS("GET_STUDENT_PROFESSORS"), GET_STUDENT_COURSES(
      "GET_STUDENT_COURSES"),
  INSERT_PROFESSOR_RATING("INSERT_PROFESSOR_RATING"),
  GET_PROFESSOR_RATING_BY_PROFESSOR("GET_PROFESSOR_RATING_BY_PROFESSOR"),
  GET_PROFESSOR_RATING_BY_STUDENT("GET_PROFESSOR_RATING_BY_STUDENT"), SERVLET(
      "TechnionRankerServlet"), FUNCTION("FUNCTION"), COURSE("COURSE"),
  PROFESSOR("PROFESSOR"), STUDENT_USER("STUDENT_USER"),
  STUDENT_PROFESSOR_COURSE("STUDENT_PROFESSOR_COURSE"), PROFESSOR_RATING(
      "PROFESSOR_RATING"), COURSE_RATING("COURSE_RATING"),
  INSERT_COURSE_RATING("INSERT_COURSE_RATING"), GET_COURSE_RATING_BY_COURSE(
      "GET_COURSE_RATING_BY_COURSE"), GET_COURSE_RATING_BY_STUDENT(
      "GET_COURSE_RATING_BY_STUDENT"), PROFESSOR_COMMENT("PROFESSOR_COMMENT"),
  INSERT_PROFESSOR_COMMENT("INSERT_PROFESSOR_COMMENT"),
  GET_PROFESSOR_COMMENT_BY_STUDENT("GET_PROFESSOR_COMMENT_BY_STUDENT"),
  GET_PROFESSOR_COMMENT_BY_PROESSOR("GET_PROFESSOR_COMMENT_BY_PROESSOR"),
  COURSE_COMMENT("COURSE_COMMENT"), INSERT_COURSE_COMMENT(
      "INSERT_COURSE_COMMENT"), GET_COURSE_COMMENT_BY_STUDENT(
      "GET_COURSE_COMMENT_BY_STUDENT"), GET_COURSE_COMMENT_BY_COURSE(
      "GET_COURSE_COMMENT_BY_COURSE");

  private final String value;

  private TechnionRankerFunctions(String s) {
    value = s;
  }

  public String value() {
    return value;
  }
}
