package com.serverapi.utilities;

public enum TechnionRankerFunctions {
  INSERT_COURSE("INSERT_COURSE"), GET_COURSE("GET_COURSE"), INSERT_PROFESSOR(
      "INSERT_PROFESSOR"), GET_PROFESSOR("GET_PROFESSOR"), INSERT_STUDENT_USER(
      "INSERT_STUDENT_USER"), GET_STUDENT_USER("GET_STUDENT_USER"),
  INSERT_STUDENT_PROFESSOR_COURSE("INSERT_STUDENT_PROFESSOR_COURSE"),
  GET_STUDENT_PROFESSOR_COURSE("GET_STUDENT_PROFESSOR_COURSE"),
  GET_STUDENT_PROFESSORS("GET_STUDENT_PROFESSORS"), GET_STUDENT_COURSES(
      "GET_STUDENT_COURSES"),
  INSERT_PROFESSOR_RATING("INSERT_PROFESSOR_RATING"),
  GET_PROFESSOR_RATING_BY_PROFESSOR("GET_PROFESSOR_RATING_BY_PROFESSOR"),
  GET_PROFESSOR_RATING_BY_STUDENT("GET_PROFESSOR_RATING_BY_STUDENT"), SERVLET(
      "TechnionRankerServlet"), FUNCTION("FUNCTION"), COURSE("COURSE"),
  PROFESSOR("PROFESSOR"), STUDENT_USER("STUDENT_USER"),
  STUDENT_PROFESSOR_COURSE("STUDENT_PROFESSOR_COURSE"), PROFESSOR_RATING(
      "PROFESSOR_RATING"), COURSE_RATING("COURSE_RATING"),
  INSERT_COURSE_RATING("INSERT_COURSE_RATING"), GET_COURSE_RATING_BY_COURSE(
      "GET_COURSE_RATING_BY_COURSE"), GET_COURSE_RATING_BY_STUDENT(
      "GET_COURSE_RATING_BY_STUDENT"), PROFESSOR_COMMENT("PROFESSOR_COMMENT"),
  INSERT_PROFESSOR_COMMENT("INSERT_PROFESSOR_COMMENT"),
  GET_PROFESSOR_COMMENT_BY_STUDENT("GET_PROFESSOR_COMMENT_BY_STUDENT"),
  GET_PROFESSOR_COMMENT_BY_PROESSOR("GET_PROFESSOR_COMMENT_BY_PROESSOR"),
  COURSE_COMMENT("COURSE_COMMENT"), INSERT_COURSE_COMMENT(
      "INSERT_COURSE_COMMENT"), GET_COURSE_COMMENT_BY_STUDENT(
      "GET_COURSE_COMMENT_BY_STUDENT"), GET_COURSE_COMMENT_BY_COURSE(
      "GET_COURSE_COMMENT_BY_COURSE"), REMOVE_COURSE("REMOVE_COURSE"),
  DROP_ALL_COURSES("DROP_ALL_COURSES"), DROP_ALL_COURSE_COMMENTS(
      "DROP_ALL_COURSE_COMMENTS"), REMOVE_PROFESSOR("REMOVE_PROFESSOR"),
  DROP_ALL_PROFESSORS("DROP_ALL_PROFESSORS"), REMOVE_STUDENT_USER(
      "REMOVE_STUDENT_USER"), DROP_ALL_STUDENT_USERS("DROP_ALL_STUDENT_USERS"),
  REMOVE_STUDENT_PROFESSOR_COURSE("REMOVE_STUDENT_PROFESSOR_COURSE"),
  DROP_ALL_STUDENT_PROFESSOR_COURSES("DROP_ALL_STUDENT_PROFESSOR_COURSES"),
  REMOVE_PROFESSOR_RATING("REMOVE_PROFESSOR_RATING"),
  DROP_ALL_PROFESSOR_RATINGS("DROP_ALL_PROFESSOR_RATINGS"),
  REMOVE_COURSE_RATING("REMOVE_COURSE_RATING"), DROP_ALL_COURSE_RATINGS(
      "DROP_ALL_COURSE_RATINGS"), REMOVE_PROFESSOR_COMMENT(
      "REMOVE_PROFESSOR_COMMENT"), DROP_ALL_PROFESSOR_COMMENTS(
      "DROP_ALL_PROFESSOR_COMMENTS"), REMOVE_COURSE_COMMENT(
      "REMOVE_COURSE_COMMENT"), GET_COURSE_BY_COURSE_NUMBER(
      "GET_COURSE_BY_COURSE_NUMBER"), GET_ALL_COURSES("GET_ALL_COURSES"),
  GET_ALL_PROFESSORS("GET_ALL_PROFESSORS"), GET_PROFESSOR_BY_NAME(
      "GET_PROFESSOR_BY_NAME"), GET_PROFESSOR_BY_HEBREW_NAME(
      "GET_PROFESSOR_BY_HEBREW_NAME"), 
      GET_PROFESSOR_FOR_COURSE("GET_PROFESSOR_FOR_COURSE");

  private final String value;

  private TechnionRankerFunctions(String s) {
    value = s;
  }

  public String value() {
    return value;
  }
}
