package com.serverapi.utilities;

public enum TechnionRankerReturnCodes {
  SUCCESS("SUCCESS"), FAILED("FAILED"), BAD_PARAM("BAD_PARAM"),
  COURSE_ALREADY_EXISTS("COURSE_ALREADY_EXISTS"),
  PROESSOR_RATING_ALREADY_EXISTS("PROESSOR_RATING_ALREADY_EXISTS"),
  STUDENT_PROFESSOR_COURSE_ALREADY_EXISTS(
      "STUDENT_PROFESSOR_COURSE_ALREADY_EXISTS"), STUDENT_USER_ALREADY_EXISTS(
      "STUDENT_USER_ALREADY_EXISTS"), PROFESSOR_ALREADY_EXISTS(
      "PROFESSOR_ALREADY_EXISTS"), COURSE_RATING_ALREADY_EXISTS(
      "COURSE_RATING_ALREADY_EXISTS"), PROFESSOR_COMMENT_ALREADY_EXISTS(
      "PROFESSOR_COMMENT_ALREADY_EXISTS"), COURSE_COMMENT_ALREADY_EXISTS(
      "COURSE_COMMENT_ALREADY_EXISTS"), COURSE_DOES_NOT_EXIST(
      "COURSE_DOES_NOT_EXIST"), COURSE_COMMENT_DOES_NOT_EXIST(
      "COURSE_COMMENT_DOES_NOT_EXIST"), PROFESSOR_DOES_NOT_EXIST(
      "PROFESSOR_DOES_NOT_EXIST"), STUDENT_USER_DOES_NOT_EXIST(
      "STUDENT_USER_DOES_NOT_EXIST"),
  STUDENT_PROFESSOR_COURSE_USER_DOES_NOT_EXIST(
      "STUDENT_PROFESSOR_COURSE_USER_DOES_NOT_EXIST"),
  PROFESSOR_RATING_DOES_NOT_EXIST("PROFESSOR_RATING_DOES_NOT_EXIST"),
  COURSE_RATING_DOES_NOT_EXIST("COURSE_RATING_DOES_NOT_EXIST"),
  PROFESSOR_COMMENT_DOES_NOT_EXIST("PROFESSOR_COMMENT_DOES_NOT_EXIST");

  private final String value;

  private TechnionRankerReturnCodes(String s) {
    value = s;
  }

  public String value() {
    return value;
  }
}